### PR TITLE
Fix delayed require initial client replication bug.

### PR DESCRIPTION
**Pull request by FableRBX**

### CODE REVIEW

**Review by headjoe3 — CHANGES_REQUESTED** [review]
This reverts the change you made in #1 , so you'll have to add that `not` in there as well on line 347.

**Comment by FableRBX** [comment]
@headjoe3 After looking through and verifying today I noticed that the code on that line was actually correct and the source of the issue was in the delayed require of the Replica module on the server. It's described more thoroughly in the following dev forum post.

https://devforum.roblox.com/t/replica-an-easily-controllable-server-client-data-replication-library/254350/11?u=fablerbx

**Comment by headjoe3** [comment]
No, it's not correct; that line of code doesn't deal with when the module is required after players join, but rather when new replicants are created after the module has been required. So it was definitely still a bug, just didn't apply to your case.

**Comment by FableRBX** [comment]
I don't believe the first patch was a bug (the line 47 "not" fix) because it seems like it's meant to prevent sending duplicate replications to a client. It's only going to propagate a Replicant registered event to a client if it has already received the pre-existing Replicants upon joining and been marked in the "sentInitialReplication" table. If that line remains "not sentInitialReplication[client]", clients will no longer receive Replicant registration events after they are marked "sentInitialReplicat[client] = true".

**Comment by headjoe3** [comment]
Oh nevermind, I guess I misinterpreted what it was for. To be honest, the whole `sentInitialReplication` mechanism is probably unnecessary due to roblox's single-threaded determinism.

**Pull request merged**
